FROM python:3.9-slim
LABEL maintainer="Raghul Yogeshwar"
RUN apt-get update && apt-get upgrade -y
RUN apt-get install python3 python3-pip -y
RUN apt-get install python3-venv -y
WORKDIR /app
COPY test.py /app/
CMD ["python", "test.py"]
